export { Home } from './Home'
export { Login } from './Login'
export { Register } from './Register'
export { Profile } from './Profile'
export { Chat } from './Chat'
export { Video } from './Video'
export { Admin } from './Admin'
export { PasswordRecovery } from './PasswordRecovery';
export { Survey } from './Survey';
export { AllMembers } from './AllMembers'
export { Notifications } from './Notifications'
export { UserPosts } from './UserPosts'
